apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.application.name }}-hpa
  namespace: {{ .Values.application.namespace }}
  labels:
    app: {{ .Values.application.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.application.name }}-deploy
  minReplicas: {{ .Values.application.containers.replicas.min }}
  maxReplicas: {{ .Values.application.containers.replicas.max }}
  targetCPUUtilizationPercentage: {{ .Values.application.containers.targetCPUUtilizationPercentage }}