{{- if .Values.secret.kms }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.application.name }}-aws-kms-secret
  namespace: {{ .Values.application.namespace }}
  labels:
    app: {{ .Values.application.name }}
data:
  {{ if eq .Values.service.app.profile "dev" }}
  keyArn: YXJuOmF3czprbXM6YXAtbm9ydGhlYXN0LTI6OTM0NTYzMzE1NjgwOmtleS8yMGYyODE4NC1iMmRlLTRkNjQtOGY0ZS1kMDgwMDAwOTIyZGU=
  {{ else if eq .Values.service.app.profile "stg" }}
  keyArn: YXJuOmF3czprbXM6YXAtbm9ydGhlYXN0LTI6OTM0NTYzMzE1NjgwOmtleS8yMGYyODE4NC1iMmRlLTRkNjQtOGY0ZS1kMDgwMDAwOTIyZGU=
  {{ else if eq .Values.service.app.profile "qa" }}
  keyArn: YXJuOmF3czprbXM6YXAtbm9ydGhlYXN0LTI6MjA2MTc4MDU1NTA0OmtleS9jMmU2ZWEwNi1mZDFlLTQ5NzctOWZlNS05OWRjZmViNWIxM2E=
  {{ else if eq .Values.service.app.profile "prd" }}
  keyArn: YXJuOmF3czprbXM6YXAtbm9ydGhlYXN0LTI6MjA2MTc4MDU1NTA0OmtleS9jMmU2ZWEwNi1mZDFlLTQ5NzctOWZlNS05OWRjZmViNWIxM2E=
  {{ end }}
{{- end }}