apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.application.name }}-docker-secret
  namespace: {{ .Values.application.namespace }}
  labels:
    app: {{ .Values.application.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJkb2NrZXIuaW5uZXItdGhlaGFuZHNvbWUuY29tIjogewogICAgICAgICAgICAgICAgICAgICAgICAiYXV0aCI6ICJZV1J0YVc0NlZHaGxhR0Z1WkhNd2JXVWgiCiAgICAgICAgICAgICAgICB9CiAgICAgICAgfQp9Cg==