apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}-svc
  namespace: {{ .Values.application.namespace }}
  labels:
    app: {{ .Values.application.name }}
spec:
  selector:
    app: {{ .Values.application.name }}
  ports:
    - name: http-port
      port: {{ .Values.service.app.port }}
      targetPort: {{ .Values.service.app.targetPort }}
      protocol: TCP
