apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: karpenter-nodetemplate-front
  namespace: karpenter
spec:
  subnetSelector:
    karpenter.sh/discovery/subnetselector: '*'
  securityGroupSelector:
    karpenter.sh/discovery/securitygroupselector: '*'
  instanceProfile: aim-prd-eks-cluster-node-role
  amiSelector:
    aws::ids: "ami-0985b5b254a2d8024"
  tags:
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: optional
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 300Gi
        volumeType: gp3
        encrypted: false
        deleteOnTermination: true
  userData: |
    MIME-Version: 1.0
    Content-Type: multipart/mixed; boundary="//"

    --//
    Content-Type: text/x-shellscript; charset="us-ascii"

    #!/bin/bash
    ec2ip=$(ifconfig eth0 | grep -w inet | awk '{ print $2 }'  | tr '.' '-' )
    tagName="aim-qa-eks-cluster-front-"$ec2ip
    Instance_id=`curl -s http://169.254.169.254/latest/meta-data/instance-id/`
    vol_id=`aws ec2 describe-instances --instance-ids ${Instance_id} --region ap-northeast-2 --query 'Reservations[0].Instances[0].BlockDeviceMappings[0].Ebs.VolumeId' | sed 's/\"//g'`

    echo $(aws ec2 create-tags --resources ${Instance_id} --tags Key="Name",Value=$tagName  --region ap-northeast-2)
    echo $(aws ec2 create-tags --resources ${vol_id}  --tags Key=Name,Value=$tagName-root-ebs Key=Env,Value=qa Key=Service,Value=aim --region ap-northeast-2)

    #/opt/ds_agent/dsa_control -r
    #/opt/ds_agent/dsa_control -a dsm://10.217.249.50:4120/

    set -ex
    B64_CLUSTER_CA=LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1EUXhNVEF6TXpVeU1Gb1hEVE15TURRd09EQXpNelV5TUZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTmM1CngybXlpMThPQWxOR1FhN2V3OGR1UUdNUTdBRkV5VjNYQWd4M2YwemxSTWFtc0xOOWpzZHppRUFiYi9OY1ZMV2sKUUt0TUpvd0ZlR1NRa2FkNUMxU00yVkxMKzlTZ3c5OXRWVXZ2NkczcGVBWGlhNno0aUhEMnV0aUpTNlVzSCthcQpLbUdHY2JnVE1QMC8yYjFWRHhZaGpCdUJVOEJWc1Z0a2h5c0Z6cWlMNmxmMW1qTGQ4cWlrbHo2aWJFb01nRFYvCkY3b3QyRDR4dXA4cXV0NnMrcEh3SmFpWGlnT1hvVTI4TTArSUZ2SWU5RzgwUzNzV2Z3bGJUSFFzT1hQbU1yK3IKS3MyeVpSUSttTmJnSUdGTTJ2b0w4SitmUjhHMVJoTStzOHlYVHU2aEZXOHBKcTcyVmlqMEJNaimHNFM4aXY0NwpnY0dlUkpKa1M0ZkYyQm1VZTBjQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZEbERFNGRSWDVKTUVqWUpWOEpmWUZKVFVVYklNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSmJqVWxPNnRxcDA3THYwQmlyZgp0MkplM3IwMXJBQUlhS2V5Ty9HVXpZVzVkbGFUWStOZjhUS2VuNHV5MkhMUlJWTUJ1MW9ma1Z1UUtxekF0TVBDCkVLa3JrOXE4NkorL3U3eGNjczAzemxScWtLQU9ZTVU5NDEyRnRNTG04OEF2QjF4ZU4rQUowNVJyZXA1cWgwU1kKZTMyM2VtYXkwaUY1b3o5RWJzUGkvRHkwY3FxSmxhMVhhMTZoaWlocG1zcHcrbUxCSktuTWtvd1NNRHRSWnRmdAorZE9UNGVyVHM2aFYyc1JmdGxZZEc2TVZjV05aR2FRc0FlV2pFODkwNTZLSjZoMjExUDNDeUpQWS9NeGlIVE5PCnFBRUlWYVB2Q1RxNUdPUW5uUDB1cFcwaTVRNUZpeHU5Nnp2QkZYTk9zUkdXM2paNGZrbURhbkRQWDlsbmdWeWoKd3hBPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    API_SERVER_URL=https://1F798FFA69C8B055F44D15A69295D71D.yl4.ap-northeast-2.eks.amazonaws.com
    K8S_CLUSTER_DNS_IP=172.25.0.10
    /etc/eks/bootstrap.sh aim-qa-eks-cluster --kubelet-extra-args '--node-labels=eks.amazonaws.com/nodegroup-image=ami-0985b5b254a2d8024,eks.amazonaws.com/capacityType=ON_DEMAND,eks.amazonaws.com/nodegroup=aim-qa-eks-front-ng,node-group=front' --b64-cluster-ca $B64_CLUSTER_CA --apiserver-endpoint $API_SERVER_URL --dns-cluster-ip $K8S_CLUSTER_DNS_IP
    --//--

---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: karpenter-nodetemplate-app
  namespace: karpenter
spec:
  subnetSelector:
    karpenter.sh/discovery/subnetselector: '*'
  securityGroupSelector:
    karpenter.sh/discovery/securitygroupselector: '*'
  instanceProfile: aim-prd-eks-cluster-node-role
  amiSelector:
    aws::ids: "ami-0985b5b254a2d8024"
  tags:
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: optional
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 100Gi
        volumeType: gp3
        encrypted: false
        deleteOnTermination: true
  userData: |
    MIME-Version: 1.0
    Content-Type: multipart/mixed; boundary="//"

    --//
    Content-Type: text/x-shellscript; charset="us-ascii"

    #!/bin/bash
    ec2ip=$(ifconfig eth0 | grep -w inet | awk '{ print $2 }'  | tr '.' '-' )
    tagName="aim-qa-eks-cluster-app-"$ec2ip
    Instance_id=`curl -s http://169.254.169.254/latest/meta-data/instance-id/`
    vol_id=`aws ec2 describe-instances --instance-ids ${Instance_id} --region ap-northeast-2 --query 'Reservations[0].Instances[0].BlockDeviceMappings[0].Ebs.VolumeId' | sed 's/\"//g'`

    echo $(aws ec2 create-tags --resources ${Instance_id} --tags Key="Name",Value=$tagName  --region ap-northeast-2)
    echo $(aws ec2 create-tags --resources ${vol_id}  --tags Key=Name,Value=$tagName-root-ebs Key=Env,Value=qa Key=Service,Value=aim --region ap-northeast-2)

    #/opt/ds_agent/dsa_control -r
    #/opt/ds_agent/dsa_control -a dsm://10.217.249.50:4120/

    set -ex
    B64_CLUSTER_CA=LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1EUXhNVEF6TXpVeU1Gb1hEVE15TURRd09EQXpNelV5TUZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTmM1CngybXlpMThPQWxOR1FhN2V3OGR1UUdNUTdBRkV5VjNYQWd4M2YwemxSTWFtc0xOOWpzZHppRUFiYi9OY1ZMV2sKUUt0TUpvd0ZlR1NRa2FkNUMxU00yVkxMKzlTZ3c5OXRWVXZ2NkczcGVBWGlhNno0aUhEMnV0aUpTNlVzSCthcQpLbUdHY2JnVE1QMC8yYjFWRHhZaGpCdUJVOEJWc1Z0a2h5c0Z6cWlMNmxmMW1qTGQ4cWlrbHo2aWJFb01nRFYvCkY3b3QyRDR4dXA4cXV0NnMrcEh3SmFpWGlnT1hvVTI4TTArSUZ2SWU5RzgwUzNzV2Z3bGJUSFFzT1hQbU1yK3IKS3MyeVpSUSttTmJnSUdGTTJ2b0w4SitmUjhHMVJoTStzOHlYVHU2aEZXOHBKcTcyVmlqMEJNaimHNFM4aXY0NwpnY0dlUkpKa1M0ZkYyQm1VZTBjQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZEbERFNGRSWDVKTUVqWUpWOEpmWUZKVFVVYklNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSmJqVWxPNnRxcDA3THYwQmlyZgp0MkplM3IwMXJBQUlhS2V5Ty9HVXpZVzVkbGFUWStOZjhUS2VuNHV5MkhMUlJWTUJ1MW9ma1Z1UUtxekF0TVBDCkVLa3JrOXE4NkorL3U3eGNjczAzemxScWtLQU9ZTVU5NDEyRnRNTG04OEF2QjF4ZU4rQUowNVJyZXA1cWgwU1kKZTMyM2VtYXkwaUY1b3o5RWJzUGkvRHkwY3FxSmxhMVhhMTZoaWlocG1zcHcrbUxCSktuTWtvd1NNRHRSWnRmdAorZE9UNGVyVHM2aFYyc1JmdGxZZEc2TVZjV05aR2FRc0FlV2pFODkwNTZLSjZoMjExUDNDeUpQWS9NeGlIVE5PCnFBRUlWYVB2Q1RxNUdPUW5uUDB1cFcwaTVRNUZpeHU5Nnp2QkZYTk9zUkdXM2paNGZrbURhbkRQWDlsbmdWeWoKd3hBPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    API_SERVER_URL=https://1F798FFA69C8B055F44D15A69295D71D.yl4.ap-northeast-2.eks.amazonaws.com
    K8S_CLUSTER_DNS_IP=172.25.0.10
    /etc/eks/bootstrap.sh aim-qa-eks-cluster --kubelet-extra-args '--node-labels=eks.amazonaws.com/nodegroup-image=ami-0985b5b254a2d8024,eks.amazonaws.com/capacityType=ON_DEMAND,eks.amazonaws.com/nodegroup=aim-qa-eks-app-ng,node-group=app' --b64-cluster-ca $B64_CLUSTER_CA --apiserver-endpoint $API_SERVER_URL --dns-cluster-ip $K8S_CLUSTER_DNS_IP
    --//--

---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: karpenter-nodetemplate-batch
  namespace: karpenter
spec:
  subnetSelector:
    karpenter.sh/discovery/subnetselector: '*'
  securityGroupSelector:
    karpenter.sh/discovery/securitygroupselector: '*'
  instanceProfile: aim-prd-eks-cluster-node-role
  amiSelector:
    aws::ids: "ami-0985b5b254a2d8024"
  tags:
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: optional
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 100Gi
        volumeType: gp3
        encrypted: false
        deleteOnTermination: true
  userData: |
    MIME-Version: 1.0
    Content-Type: multipart/mixed; boundary="//"

    --//
    Content-Type: text/x-shellscript; charset="utf8"

    #!/bin/bash
    ec2ip=$(ifconfig eth0 | grep -w inet | awk '{ print $2 }'  | tr '.' '-' )
    tagName="aim-qa-eks-cluster-batch-"$ec2ip
    Instance_id=`curl -s http://169.254.169.254/latest/meta-data/instance-id/`
    vol_id=`aws ec2 describe-instances --instance-ids ${Instance_id} --region ap-northeast-2 --query 'Reservations[0].Instances[0].BlockDeviceMappings[0].Ebs.VolumeId' | sed 's/\"//g'`

    echo $(aws ec2 create-tags --resources ${Instance_id} --tags Key="Name",Value=$tagName  --region ap-northeast-2)
    echo $(aws ec2 create-tags --resources ${vol_id}  --tags Key=Name,Value=$tagName-root-ebs Key=Env,Value=qa Key=Service,Value=aim --region ap-northeast-2)

    #/opt/ds_agent/dsa_control -r
    #/opt/ds_agent/dsa_control -a dsm://10.217.249.50:4120/

    set -ex
    B64_CLUSTER_CA=LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1EUXhNVEF6TXpVeU1Gb1hEVE15TURRd09EQXpNelV5TUZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTmM1CngybXlpMThPQWxOR1FhN2V3OGR1UUdNUTdBRkV5VjNYQWd4M2YwemxSTWFtc0xOOWpzZHppRUFiYi9OY1ZMV2sKUUt0TUpvd0ZlR1NRa2FkNUMxU00yVkxMKzlTZ3c5OXRWVXZ2NkczcGVBWGlhNno0aUhEMnV0aUpTNlVzSCthcQpLbUdHY2JnVE1QMC8yYjFWRHhZaGpCdUJVOEJWc1Z0a2h5c0Z6cWlMNmxmMW1qTGQ4cWlrbHo2aWJFb01nRFYvCkY3b3QyRDR4dXA4cXV0NnMrcEh3SmFpWGlnT1hvVTI4TTArSUZ2SWU5RzgwUzNzV2Z3bGJUSFFzT1hQbU1yK3IKS3MyeVpSUSttTmJnSUdGTTJ2b0w4SitmUjhHMVJoTStzOHlYVHU2aEZXOHBKcTcyVmlqMEJNaimHNFM4aXY0NwpnY0dlUkpKa1M0ZkYyQm1VZTBjQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZEbERFNGRSWDVKTUVqWUpWOEpmWUZKVFVVYklNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSmJqVWxPNnRxcDA3THYwQmlyZgp0MkplM3IwMXJBQUlhS2V5Ty9HVXpZVzVkbGFUWStOZjhUS2VuNHV5MkhMUlJWTUJ1MW9ma1Z1UUtxekF0TVBDCkVLa3JrOXE4NkorL3U3eGNjczAzemxScWtLQU9ZTVU5NDEyRnRNTG04OEF2QjF4ZU4rQUowNVJyZXA1cWgwU1kKZTMyM2VtYXkwaUY1b3o5RWJzUGkvRHkwY3FxSmxhMVhhMTZoaWlocG1zcHcrbUxCSktuTWtvd1NNRHRSWnRmdAorZE9UNGVyVHM2aFYyc1JmdGxZZEc2TVZjV05aR2FRc0FlV2pFODkwNTZLSjZoMjExUDNDeUpQWS9NeGlIVE5PCnFBRUlWYVB2Q1RxNUdPUW5uUDB1cFcwaTVRNUZpeHU5Nnp2QkZYTk9zUkdXM2paNGZrbURhbkRQWDlsbmdWeWoKd3hBPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    API_SERVER_URL=https://1F798FFA69C8B055F44D15A69295D71D.yl4.ap-northeast-2.eks.amazonaws.com
    K8S_CLUSTER_DNS_IP=172.25.0.10
    /etc/eks/bootstrap.sh aim-qa-eks-cluster --kubelet-extra-args '--node-labels=eks.amazonaws.com/nodegroup-image=ami-0985b5b254a2d8024,eks.amazonaws.com/capacityType=ON_DEMAND,eks.amazonaws.com/nodegroup=aim-qa-eks-batch-ng,node-group=batch' --b64-cluster-ca $B64_CLUSTER_CA --apiserver-endpoint $API_SERVER_URL --dns-cluster-ip $K8S_CLUSTER_DNS_IP
    --//--
