# Default values for dev.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

gateway:
  name: aim-inner-thehandsome-gw
  namespace: aim-gateway
  host:
    -  "bow.inner-test.com"
    -  "ccw.inner-test.com"
    -  "gw.inner-test.com"
    -  "api-member.inner-test.com"
    -  "api-goods.inner-test.com"
    -  "api-display.inner-test.com"
    -  "api-event.inner-test.com"
    -  "api-common.inner-test.com"
    -  "api-order.inner-test.com"
    -  "api-bo.inner-test.com"
    -  "batch-mbod.inner-test.com"
    -  "batch-gddp.inner-test.com"