# Gateway Template

---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.gateway.namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        {{- range .Values.gateway.host }}
        - {{.}}{{- end }}
    - port:
        number: 443
        name: https
        protocol: HTTP
      hosts:
        {{- range .Values.gateway.host }}
        - {{.}}{{- end }}