version: "2"

services:
  jenkins:
    image: docker.inner-test.com/library/jenkins:dev-backup
    restart: always
    user: root
    container_name: jenkins
    volumes:
      - "/apps/jenkins/jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "80:8080"