services:
  nexus:
    #image: docker.inner-test.com/library/nexus:3.37.3 
    image: sonatype/nexus3:3.37.3
    restart: always
    user: root
    container_name: nexus
    volumes:
      - "/apps/nexus/nexus-data:/nexus-data"
    ports:
      - "8081:8081"
      - "5000:5000"