apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2024-07-04T02:12:40Z"
  generation: 1
  labels:
    istio.io/rev: default
    operator.istio.io/component: IstioOperator
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.22.1
  name: istio-operator
  namespace: istio-operator
  resourceVersion: "235484403"
  uid: cab26816-536f-4c84-92f5-68081e79f97a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: istio-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/port: "15014"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        name: istio-operator
    spec:
      containers:
      - command:
        - operator
        - server
        - --monitoring-host=127.0.0.1
        - --monitoring-port=15014
        env:
        - name: WATCH_NAMESPACE
          value: istio-system
        - name: LEADER_ELECTION_NAMESPACE
          value: istio-operator
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: istio-operator
        - name: WAIT_FOR_RESOURCES_TIMEOUT
          value: 300s
        - name: REVISION
        image: docker.io/istio/operator:1.22.1
        imagePullPolicy: IfNotPresent
        name: istio-operator
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: istio-operator
      serviceAccountName: istio-operator
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-07-04T02:12:40Z"
    lastUpdateTime: "2024-07-04T02:12:47Z"
    message: ReplicaSet "istio-operator-5c7cc75897" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-07-05T00:04:33Z"
    lastUpdateTime: "2024-07-05T00:04:33Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
