#front
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: karpenter-provisioner-front
spec:
  providerRef:
    name: karpenter-nodetemplate-front
  requirements:
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["m5.2xlarge"] # 8core/32mem
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["ap-northeast-2a", "ap-northeast-2b", "ap-northeast-2c"]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["on-demand"]
  labels:
    node-group: front
  limits:  # Provisioner에서 할당할 수 있는 리소스를 제한
    resources:
      cpu: "400"
      memory: 1600Gi
  consolidation: # 워크로드 변동에 따른 노드의 종료 및 교체를 적극적으로 개입하는 옵션
    enabled: false
  ttlSecondsUntilExpired: 604800 # 노드의 최대 수명 주기(7일)
  ttlSecondsAfterEmpty: 180 # DaemonSet을 제외한 노드 내 리소스가 없는 경우 설정값 이후 노드 종료(3분)

#app
--- 
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: karpenter-provisioner-app
spec:
  providerRef:
    name: karpenter-nodetemplate-app
  requirements:
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["m5.2xlarge"] # 8core/32mem
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["ap-northeast-2a", "ap-northeast-2b", "ap-northeast-2c"]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["on-demand"]
  labels:
    node-group: app
  limits:  # Provisioner에서 할당할 수 있는 리소스를 제한
    resources:
      cpu: "800"
      memory: 3200Gi
  consolidation: # 워크로드 변동에 따른 노드의 종료 및 교체를 적극적으로 개입하는 옵션
    enabled: false
  ttlSecondsUntilExpired: 604800 # 노드의 최대 수명 주기(7일)
  ttlSecondsAfterEmpty: 180 # DaemonSet을 제외한 노드 내 리소스가 없는 경우 설정값 이후 노드 종료(3분)

#batch
--- 
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: karpenter-provisioner-batch
spec:
  providerRef:
    name: karpenter-nodetemplate-batch
  requirements:
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["c5.xlarge"] # 4core/8mem
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["ap-northeast-2a", "ap-northeast-2b", "ap-northeast-2c"]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["on-demand"]
  labels:
    node-group: batch
  limits:  # Provisioner에서 할당할 수 있는 리소스를 제한
    resources:
      cpu: "100"
      memory: 200Gi
  consolidation: # 워크로드 변동에 따른 노드의 종료 및 교체를 적극적으로 개입하는 옵션
    enabled: false
  ttlSecondsUntilExpired: 604800 # 노드의 최대 수명 주기(7일)
  ttlSecondsAfterEmpty: 180 # DaemonSet을 제외한 노드 내 리소스가 없는 경우 설정값 이후 노드 종료(3분)
